**Uploading Dataset**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ev_charging_raw_data.csv')
df.head()

,Station_ID,City,Install_Date,Charger_Type,Daily_Avg_Utilization_Hrs,Avg_Charging_Rate_INR,Electricity_Cost_INR,Total_Energy_Dispensed_kWh,Maintenance_Incidents,Total_Maintenance_Cost_INR,Operational_Status,Install_Cost_INR
0,EV-0001,Hyderabad,2023/10/17,L2,4.114846,20.925642,7.165687,75105.476693,6,22618.009068,Active,2.260929e+05
1,EV-0002,Kochi,25-04-2022,DCFC,4.115988,17.493129,8.583443,36252.305095,6,11685.221551,Active,1.457005e+06
2,EV-0003,Bangalore,2022/01/26,DCFC,6.888372,17.293584,7.846512,57363.368182,4,32122.421956,Active,1.518839e+06
3,EV-0004,Kochi,2024/01/30,L2,1.658703,17.226949,5.940195,42837.138666,2,15610.404385,Active,1.649651e+05
4,EV-0005,Kochi,2022/10/09,L2,5.299494,20.232640,6.413898,54918.077273,4,11618.158385,Active,2.683064e+05

**Cleaning and Transforming Data**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Station_ID                  1200 non-null   object
 1   City                        1200 non-null   object
 2   Install_Date                1200 non-null   object
 3   Charger_Type                1140 non-null   object
 4   Daily_Avg_Utilization_Hrs   1142 non-null   float64
 5   Avg_Charging_Rate_INR       1200 non-null   float64
 6   Electricity_Cost_INR        1200 non-null   float64
 7   Total_Energy_Dispensed_kWh  1140 non-null   float64
 8   Maintenance_Incidents       1200 non-null   int64
 9   Total_Maintenance_Cost_INR  1141 non-null   float64
 10  Operational_Status          1200 non-null   object
 11  Install_Cost_INR            1200 non-null   float64
dtypes: float64(6), int64(1), object(5)
memory usage: 112.6+ KB

In [ ]:
df.describe()

,Daily_Avg_Utilization_Hrs,Avg_Charging_Rate_INR,Electricity_Cost_INR,Total_Energy_Dispensed_kWh,Maintenance_Incidents,Total_Maintenance_Cost_INR,Install_Cost_INR
count,1142.000000,1200.000000,1200.000000,1140.000000,1200.000000,1141.000000,1.200000e+03
mean,7.742385,18.468030,8.006696,50246.851586,3.177500,15276.529761,5.936883e+05
std,5.633165,2.006550,0.975584,15181.749512,1.828601,6284.323901,5.924514e+05
min,-1.967034,11.821000,4.954071,556.204820,0.000000,-4904.863757,0.000000e+00
25%,5.103067,17.022543,7.357689,39796.782389,2.000000,11333.144228,2.000151e+05
50%,6.903651,18.475407,7.980317,50626.318119,3.000000,15443.549817,2.514516e+05
75%,8.758682,19.906127,8.670851,60775.163298,4.000000,19304.146702,1.295130e+06
max,47.907403,24.341505,12.052550,91984.692954,11.000000,37750.943089,1.792805e+06

**Rounding Float Values to 2 Decimal Points**

In [ ]:
float_columns = df.select_dtypes(include=['float64']).columns
df[float_columns] = df[float_columns].round(2)
print (df[['Daily_Avg_Utilization_Hrs','Electricity_Cost_INR','Install_Cost_INR']].head())

   Daily_Avg_Utilization_Hrs  Electricity_Cost_INR  Install_Cost_INR
0                       4.11                  7.17         226092.86
1                       4.12                  8.58        1457005.43
2                       6.89                  7.85        1518838.98
3                       1.66                  5.94         164965.07
4                       5.30                  6.41         268306.43

**Correcting the Spelling Incorrections**

In [ ]:
Charger_replace = {'l2' : 'L2', 'dcfc' : 'DCFC'}
df['Charger_Type'] = df['Charger_Type'].str.strip().replace(Charger_replace)
print (df['Charger_Type'].value_counts())

City_replace = {'BANGALORE' : 'Bangalore', 'hydrabad' : 'Hyderabad', 'Coimbator' : 'Coimbatore', 'chennai':'Chennai'}
df['City'] = df['City'].str.strip().replace(City_replace)
print (df['City'].value_counts())

Charger_Type
L2      801
DCFC    339
Name: count, dtype: int64
City
Madurai       214
Hyderabad     210
Chennai       208
Kochi         194
Coimbatore    188
Bangalore     186
Name: count, dtype: int64

**Dropping Rows with Zeros and Converting Negatives**

In [ ]:
df['Install_Cost_INR'] = df['Install_Cost_INR'].abs()
df['Electricity_Cost_INR'] = df['Electricity_Cost_INR'].abs()
df['Avg_Charging_Rate_INR'] = df['Avg_Charging_Rate_INR'].abs()
df['Total_Energy_Dispensed_kWh'] = df['Total_Energy_Dispensed_kWh'].abs()
df['Total_Maintenance_Cost_INR'] = df['Total_Maintenance_Cost_INR'].abs()
df['Daily_Avg_Utilization_Hrs'] = df['Daily_Avg_Utilization_Hrs'].abs()
df = df[df['Total_Energy_Dispensed_kWh']!=0]
df = df[df['Total_Maintenance_Cost_INR']!=0]
df = df[df['Daily_Avg_Utilization_Hrs']!=0]
df = df[df['Avg_Charging_Rate_INR']!=0]
df = df[df['Install_Cost_INR']!=0]
df = df[df['Electricity_Cost_INR']!=0]
df.describe()

,Daily_Avg_Utilization_Hrs,Avg_Charging_Rate_INR,Electricity_Cost_INR,Total_Energy_Dispensed_kWh,Maintenance_Incidents,Total_Maintenance_Cost_INR,Install_Cost_INR
count,1130.000000,1188.000000,1188.000000,1128.000000,1188.000000,1129.000000,1.188000e+03
mean,7.761000,18.467407,8.006894,50304.283094,3.180135,15379.185731,5.996851e+05
std,5.646275,1.996496,0.973597,15196.323822,1.828689,5992.810227,5.924085e+05
min,0.020000,11.820000,4.950000,556.200000,0.000000,49.710000,1.501885e+05
25%,5.102500,17.040000,7.360000,39830.835000,2.000000,11311.790000,2.018608e+05
50%,6.905000,18.480000,7.980000,50669.585000,3.000000,15449.290000,2.530027e+05
75%,8.767500,19.902500,8.670000,60815.462500,4.000000,19304.150000,1.301224e+06
max,47.910000,24.340000,12.050000,91984.690000,11.000000,37750.940000,1.792805e+06

**Handling Null Values**

In [ ]:
print (df.isnull().sum())

Station_ID                     0
City                           0
Install_Date                   0
Charger_Type                  58
Daily_Avg_Utilization_Hrs     58
Avg_Charging_Rate_INR          0
Electricity_Cost_INR           0
Total_Energy_Dispensed_kWh    60
Maintenance_Incidents          0
Total_Maintenance_Cost_INR    59
Operational_Status             0
Install_Cost_INR               0
dtype: int64

**Replacing NULL**

In [ ]:
#Removing Error Rows and Replacing NULL with Mean
df = df[df['Daily_Avg_Utilization_Hrs']<=24]
df['Daily_Avg_Utilization_Hrs'] = df['Daily_Avg_Utilization_Hrs'].fillna(df['Daily_Avg_Utilization_Hrs'].mean())

# Replacing NULL with "Unknown"
df['Charger_Type'] = df['Charger_Type'].fillna('Unknown')


#Replacing NULL with Grouped Average
df['Total_Energy_Dispensed_kWh'] = df['Total_Energy_Dispensed_kWh'].fillna(df.groupby(['City','Charger_Type'])['Total_Energy_Dispensed_kWh'].transform('mean')).round(2)


df['Total_Maintenance_Cost_INR'] = df['Total_Maintenance_Cost_INR'].fillna(df.groupby(['City','Charger_Type'])['Total_Maintenance_Cost_INR'].transform('mean')).round(2)
print (df.isnull().sum())

Station_ID                    0
City                          0
Install_Date                  0
Charger_Type                  0
Daily_Avg_Utilization_Hrs     0
Avg_Charging_Rate_INR         0
Electricity_Cost_INR          0
Total_Energy_Dispensed_kWh    0
Maintenance_Incidents         0
Total_Maintenance_Cost_INR    0
Operational_Status            0
Install_Cost_INR              0
dtype: int64

**Converting Object to Date format**

In [ ]:
df['Install_Date'] = pd.to_datetime(df['Install_Date'], dayfirst=True, format = 'mixed')
df.head()

,Station_ID,City,Install_Date,Charger_Type,Daily_Avg_Utilization_Hrs,Avg_Charging_Rate_INR,Electricity_Cost_INR,Total_Energy_Dispensed_kWh,Maintenance_Incidents,Total_Maintenance_Cost_INR,Operational_Status,Install_Cost_INR
0,EV-0001,Hyderabad,2023-10-17,L2,4.11,20.93,7.17,75105.48,6,22618.01,Active,226092.86
1,EV-0002,Kochi,2022-04-25,DCFC,4.12,17.49,8.58,36252.31,6,11685.22,Active,1457005.43
2,EV-0003,Bangalore,2022-01-26,DCFC,6.89,17.29,7.85,57363.37,4,32122.42,Active,1518838.98
3,EV-0004,Kochi,2024-01-30,L2,1.66,17.23,5.94,42837.14,2,15610.40,Active,164965.07
4,EV-0005,Kochi,2022-10-09,L2,5.30,20.23,6.41,54918.08,4,11618.16,Active,268306.43

**Creating New Columns**

In [ ]:
# Total_Revenue
df['Total_Revenue'] = (df['Avg_Charging_Rate_INR']*df['Total_Energy_Dispensed_kWh']).round(2)

# Total_Operational_Cost
df['Total_Operational_Cost'] = ((df['Total_Energy_Dispensed_kWh']*df['Electricity_Cost_INR']) + df['Total_Maintenance_Cost_INR']).round(2)

# Net_Profit
df['Net_Profit'] = (df['Total_Revenue'] - df['Total_Operational_Cost']).round(2)

# ROI
df['ROI'] = ((df['Net_Profit']/df['Install_Cost_INR'])*100).round(2)

**Exporting the Cleaned DataSet**

In [ ]:
df.to_csv("ev_charging_cleaned_data.csv", index = False)